[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 35

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/hello-github-ui/hello-github-ui.github.io"
  weight = 40

[[main]]
  name = "友链"
  weight = 50

[[main]]
  name = "mdviewer"
  parent = "友链"
  url = "https://mdviewer-fceu.onrender.com/docs/intro"
  weight = 10

[[main]]
  name = "面试题"
  parent = "友链"
  url = "https://hello-github-ui.github.io/exams/#/"
  weight = 20

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "归档"
  pageRef = "archives"
  weight = 40
