colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

replyByEmail = false
mainSections = ["posts"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "img/site-background.svg"
backgroundCanvas = true
hotlinkFeatureImage = false
defaultFeaturedImage = "featured.png"
fingerprintAlgorithm = "sha512"
highlightCurrentMenuArea = true
smartTOC = true

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[languageRedirect]
  enabled = false
  storageKey = "blowfish_preferred_language"
  browserRedirectHomeOnly = true
  storedLanguageRedirect = true

[header]
  layout = "floating"
  mobileMenuStyle = "dropdown"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "landing"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true
  disableHeroImageFilter = false

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showReadingProgress = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showCategories = true
  showTags = true
  showCategoriesInSecondaryColor = true
  showAuthorsBadges = false
  showWordCount = true
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showSummary = false
  showViews = true
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showViews = true
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showViews = true
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]
  apiKey = ""
  authDomain = ""
  projectId = ""
  storageBucket = ""
  messagingSenderId = ""
  appId = ""
  measurementId = ""
[fathomAnalytics]
[umamiAnalytics]
[selineAnalytics]
[buymeacoffee]
[verification]
[rssnext]
[advertisement]
